title: Mysticism Demystified
baseurl: "" # leave blank for custom domain
url: "https://maram.cc"

markdown: kramdown
theme: null  # You are overriding the theme with a custom layout

collections:
  chapters:
    output: true
    permalink: /chapters/:name.html

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "_chapters"
    values:
      layout: default

feed:
  path: feed.xml

